#!/bin/sh

cat <<\EOF
Info: This is just a commit tests.
EOF

#The Git diff-index identifies the code increment committed in the script. This increment is then compared against the list of specified keywords. 
#If any matches are found, an error is raised to block the commit;
matches=$(git diff-index --patch HEAD | grep '^+' | grep -Pi 'password|keyword2|keyword3')
if [ ! -z "$matches" ]
then 
	cat <<\EOT
Error: Words from the blocked list were present in the diff:
EOT
	echo $matches
	exit 1 	
fi